name: Lint Code Base

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_JAVA: true
          JAVA_FILE_NAME: checkstyle.xml
          VALIDATE_JAVA_MAVEN: true
          VALIDATE_JAVA_GRADLE: false
